!/bin/sh

# cleanup
rm -rf obj_dir
rm -f f1_second.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace f1_second.sv --exe f1_second_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vf1_second.mk Vf1_second

# run executable simulation file
echo "\nRunning simulation"
obj_dir/Vf1_second
echo "\nSimulation completed"

